package com.dev.schedulecalculation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessInputData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ProcessInputData() {
    }




}