package com.dev.schedulecalculation;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ProcessData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROCESSDATA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "PROCESSDATA_ID_GENERATOR", sequenceName = "PROCESSDATA_ID_SEQ")
    private java.lang.Long id;

    public ProcessData() {
    }
    
    public ProcessData(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}